### ISSUE TITLE
Can't login on Mac, version 5.5.22

### ISSUE THREAD

**Issue by jbancroftconnors** [Manuel-777/MTG-Arena-Tool#1267] opened 2021-09-10 22:10 UTC
Just installed it on my MacBook Pro. I enter my login credentials and hit the login button. The button doesn't even react like a button and nothing happens.

**Comment by riQQ** [comment] 2021-09-13 06:35
Duplicate of #1266.

**Closed by riQQ** 2021-09-13 06:35 UTC
