### ISSUE TITLE
Tool does not show content on the different tabs

### ISSUE THREAD

**Issue by ndee811** [Manuel-777/MTG-Arena-Tool#81] opened 2018-10-31 19:50 UTC
Repro Steps:
start tool
continue offline
->now it shows my decks
->i change to any tab for example history
-> no matches are shown
-> i change back to my decks
-> no decks are shown

This bug exists since today. Yesterday the tool was still working fine.

**Comment by Manuel-777** [comment] 2018-10-31 20:50
Duplicate of #79, closing

**Closed by Manuel-777** 2018-10-31 20:50 UTC
