### ISSUE TITLE
Eldraine collection is shown as incorrect

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1003] opened 2020-04-19 04:08 UTC
See joined screenshot.
I'm 100% complete for commons, uncos and rares of Eldraine, only mythics are incomplete, through since latest updates those are shown as incomplete with some of the cards on top counted at 0 copies.

I checked every set, strangely only Eldraine seems to be affected.

![collection_bug_eldraine](https://user-images.githubusercontent.com/709500/79679205-1c082f80-8204-11ea-96b3-6e096ec4f8b4.PNG)

**Comment by Manuel-777** [comment] 2020-04-19 18:15
Duplicate of #999

**Closed by Manuel-777** 2020-04-19 18:15 UTC
