### ISSUE TITLE
Card Collection Error (again)

### ISSUE THREAD

**Issue by Muffalopadus** [Manuel-777/MTG-Arena-Tool#1146] opened 2020-07-17 02:52 UTC
An issue that you have previously fixed has popped up again. 

In at least WAR, GRN, M20, and ELD there are cards in the collection view that have a duplicate with no collected cards, in both the cards and sets view.
![MTG-Arena-Tool_2D19Bntu2X](https://user-images.githubusercontent.com/66968752/87743399-d7664300-c7b6-11ea-9359-7e7b0a64baa7.png)
![MTG-Arena-Tool_ut4ULgBX9k](https://user-images.githubusercontent.com/66968752/87743406-d9c89d00-c7b6-11ea-8beb-2ee417452f6d.png)
Hard to tell if its in other sets due to my collection not being as complete.

**Comment by Muffalopadus** [comment] 2020-07-17 02:56
After doing a little more research, these are almost certainly the "jumpstart" versions of these cards.

**Comment by Manuel-777** [comment] 2020-07-17 04:43
Yep, not a bug, there are two actual entries of the cards in the Arena cards data, and you can effectively have 8 copies of those cards.

**Comment by riQQ** [comment] 2020-07-17 08:38
But them having the same icon is a bug no?

**Comment by Manuel-777** [comment] 2020-07-17 14:07
Its a database issue, Ill see if I can "hack" the game so it adds them to JMP instead of both to WAR (and so on for the rest)

**Comment by Manuel-777** [comment] 2020-07-17 14:12
BTW scryfall added them to a new set;
https://scryfall.com/sets/ajmp

**Comment by Manuel-777** [comment] 2020-07-17 20:29
This should be fixed now

**Closed by Manuel-777** 2020-07-17 20:29 UTC
Labels: apparently fixed, database
