### ISSUE TITLE
Game duration shown as 00:00

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1004] opened 2020-04-19 04:20 UTC
See joined screenshot, since update game duration is shown as 00:00.
![partial_translation_wrong_duration](https://user-images.githubusercontent.com/709500/79679383-eb28fa00-8205-11ea-8ca8-46804bbed86b.PNG)

**Comment by LuckyBlack72** [comment] 2020-04-19 07:56
![image](https://user-images.githubusercontent.com/42611122/79682628-0efb3880-8224-11ea-9fcb-ee883cc4ab7c.png)

here the same

**Comment by Thaoden** [comment] 2020-04-19 10:30
duplicate of #998

**Closed by Thaoden** 2020-04-19 10:30 UTC
