### ISSUE TITLE
Cannot close "what's new" window

### ISSUE THREAD

**Issue by Nolivfr** [Manuel-777/MTG-Arena-Tool#516] opened 2019-08-06 14:35 UTC
Hi,

I have a bug when I open the tool after an update, there is no close button on the "what's new" splash screen and I can't access the MTGA tool.

I have to reinstall the program for the splash screen to disappear.

I had the bug with v2.8.1 (I think, not sure), 2.8.6 and 2.8.7.

**Comment by riQQ** [comment] 2019-08-06 18:48
Just click somewhere outside of the popup but inside MTG Arena Tool.

**Comment by Nolivfr** [comment] 2019-08-07 01:08
It doesn't work, I can't click anywhere, the splash screen as the focus.
I can reduce it or close it to the taskbar but the splash screen is still there.

I can only close MTGATool by right clicking it in the taskbar and closing it. I must then reinstall the same version and the splash screen disappear.

**Comment by Manuel-777** [comment] 2019-08-07 02:13
Closing from **system tray** and starting again normally should make the popup disappear for that version, but as stated above, clocking outside of the popup works just fine. Closing from taskbar simply minimizes the app to the tray (you can change that behavior in settings)

**Comment by AnnanFay** [comment] 2019-10-02 01:23
> I can't click anywhere

If I understand correctly the bug here appears to be that when the splash screen appears clicking outside of the splash screen does not close the splash screen as it normally should.

This may be related to the persistent "Loading Screen" which caused the entire screen to freeze. Though this hasn't been an issue recently, so maybe the most recent version has fixed everything.

I can't reproduce this, and haven't seen any other reports of this happening. I'm going to mark this as not reproducible and close it. **If this is still happening please reopen the issue.**

Clicking the `Esc` key might also work to close the splash window if clicking on the background fails.

**Closed by AnnanFay** 2019-10-02 01:23 UTC
