### ISSUE TITLE
Main area of the window regularly become empty

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#612] opened 2019-10-05 06:29 UTC
See the joined screenshot.

This happens in similar circumstances as #546 was (I'm not sure, but it's possible the other issue still shows up).

User just regularly use MTG Arena Tool… and gets the main area's content in the window disappearing, and have to switch on another one and back on it to get content back.

![Empty screen](https://user-images.githubusercontent.com/709500/66250968-40aa2780-e74a-11e9-8f9f-44735f7fea96.PNG)

**Comment by Manuel-777** [comment] 2019-10-05 13:53
Can you replicate the issue at will? I need to replicate to find where the problem is

**Comment by Porkepix** [comment] 2019-10-05 14:38
Sadly not, this is pretty random :(
Maybe can I gather some useful logs somehow, though?

**Comment by Porkepix** [comment] 2019-11-02 11:57
@Manuel-777 There's still the "needs more data" label, but I don't know how to provide more inputs, any pointer on that? (Issue still regularly happens, especially in the collection statistics tab I believe, but not limited to.

**Comment by riQQ** [comment] 2019-11-03 14:18
I don't know what triggers it, but playing some games with the collections stats view open should reproduce the problem.

**Comment by Porkepix** [comment] 2019-11-03 15:07
> I don't know what triggers it, but playing some games with the collections stats view open should reproduce the problem.

It also happens when you're directly using it, you're about to click somewhere it the main area, and then… everything disappear.

**Comment by riQQ** [comment] 2019-11-08 23:55
I can reproduce it when starting or closing MtgA while I'm in the `Collection Stats` view.

**Comment by Manuel-777** [comment] 2020-05-05 12:59
Closing because it seems pretty random and old, renderer changed a lot since November!

**Closed by Manuel-777** 2020-05-05 12:59 UTC
Labels: needs more data

**Comment by riQQ** [comment] 2020-05-05 16:39
Can't reproduce with my steps above. Seems to be fixed.

**Comment by Porkepix** [comment] 2020-05-05 17:52
Yup, doesn't seems to reproduce anymore. It can just be a little bit slow to transition currently, but it always end up transitioning to the correct screen.
