### ISSUE TITLE
Table in collection stats can have wider columns

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1092] opened 2020-05-24 03:37 UTC
For some reasons, columns can be wider sometimes in the collection table, see the joined screenshot.

![NaN_percent_Theros2](https://user-images.githubusercontent.com/709500/82745092-9d615d80-9d80-11ea-8c39-b40ae700bb94.PNG)

**Comment by Thaoden** [comment] 2020-05-24 10:00
It is to make room for the `NaN` that you have twice (in the blank fields, if you look closely) ;).

This should be fixed already in #1089 .

**Comment by riQQ** [comment] 2020-05-24 10:29
Duplicate of #1089

**Closed by riQQ** 2020-05-24 10:29 UTC
Labels: duplicate
