### ISSUE TITLE
Arena Tool process using over 5G of memory

### ISSUE THREAD

**Issue by Melissanoma** [Manuel-777/MTG-Arena-Tool#766] opened 2019-11-27 02:51 UTC
![Untitled](https://user-images.githubusercontent.com/53976427/69689016-c042db80-1095-11ea-8ffc-aa78d8987c7a.png)

Version 2.14.0

I reported another memory issue back in August, but it seems to be back now worse than ever. Previous post: https://github.com/Manuel-777/MTG-Arena-Tool/issues/524. So far this time it only happened once. I'm reporting it right away instead of waiting seeing if it repeats.

I wasn't doing anything at the time. I had actually just woken from a nap and the computer was extra slow for some reason. Arena Tool was not in the windows system tray so I didn't suspect it was the cause until I opened task manager.

**Comment by Manuel-777** [comment] 2019-11-27 03:03
Hello @Melissanoma ! You mean tool was suposed to be closed at that time? did you manually close it before leaving?

**Comment by Melissanoma** [comment] 2019-11-27 03:09
Honestly, I don't know if I closed it. I use a batch file to run MTG-Arena-Tool.exe and Mtga.exe with one click, but I often forget to close tool after closing arena. I usually notice tool's circle icon in the tray next to the clock, but it wasn't there this time. Normally I just right click the icon and quit but this time I had to end the process because there was no icon to click.

**Comment by Manuel-777** [comment] 2019-11-27 03:52
It does seem likely that due to the batch script running the process it might have failed to shut down completely when it terminated, but I cant be sure.
It should be reproducible trough; Run it then close it like you always do and check taskmgr if the arena tool process is still running.

**Closed** 2020-04-04 17:17 UTC
Labels: apparently fixed, needs more data
