### ISSUE TITLE
Hung process (Win 10)

### ISSUE THREAD

**Issue by timrolls** [Manuel-777/MTG-Arena-Tool#58] opened 2018-10-10 03:20 UTC
It seems if I have the Tool open when closing the Arena client, the tool window disappears (crashes?) and leaves a hung process in Task Manager. While in that state, new instances are also opened to a hung process. 

Current workaround is manually closing them all in task manager before opening the Tool again.

**Comment by Manuel-777** [comment] 2018-10-10 03:31
Hi Tim,

Mtgatool doesn't check if Arena is open so it's probably unrelated.
I think you might have closed the window from taskbar at some point? Since opening mtgatool again will only restore the old process and close the new one to avoid duplicate instances.
So, Do you see the tray icon? Did you close from taskbar or from the app close button? Can you close from tray?

**Comment by timrolls** [comment] 2018-10-10 23:15
Hmm. 

Not sure if it was closed from the taskbar. 
Didn't notice the tray icon until you mentioned it. They were also duplicated (x4), and all but one disappeared when hovered, though 4 processes remained. 

Just updated and did some more testing, and it seems to have stopped happening for now.

**Comment by Manuel-777** [comment] 2018-10-10 23:50
Ok, closing. But don't hesitate to open it back if you encounter the issue again / are able to reproduce it :)

**Closed by Manuel-777** 2018-10-10 23:50 UTC

**Comment by timrolls** [comment] 2018-10-11 02:55
Noticed the overlay wasn't working, looks like the issue is back: 
http://prntscr.com/l4ocv2
It was closed with the X on the window this time.

**Comment by Manuel-777** [comment] 2018-10-11 03:01
If you can't restore by clicking on the tray icon I think the app is failing reading the log.
Please locate your output_log file at;
%APPDATA%\..\LocalLow\Wizards Of The Coast\MTGA\

And send it to mtgatool@gmail.com for me to analyze.

**Comment by malaclypse2** [comment] 2018-10-13 19:06
This happens to me a lot too.  

The overlay stops working, and new matches are not being parsed for history.  The app itself seems to still work, except for those things.  Closing the app at this point often leaves a stray process running, and no new instance can be started until all the strays are cleaned up in process manager.  Once the app is restarted, logs are parsed and added to my history, and everything will work fine for a few matches, then the same thing happens again.

If it matters, I have "Close to tray" turned off in the options.

**Comment by malaclypse2** [comment] 2018-10-13 21:44
Sure thing.  As usual, as soon as I comment on the bug report, I can no longer reproduce the issue on demand. I'll send a log next time it happens.
