### ISSUE TITLE
Overlay regression in bringing it to foreground but not locked on top

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#520] opened 2019-08-08 02:08 UTC
I can't say since which release, but it's a recent one. I would say two to three weeks ago maximum.

I'm playing on an old screen with a 1280x1024 resolution, resulting in mtga refusing to run as fullscreen and only offering really weird window formats. Due to this screen format, MTG-Arena-Tool overlays would partly recover game's window, which isn't nice.

Previous behavior had it to bring overlays when a game or a draft was starting, but keep it on the layer just under the game with the lock option unchecked. This way, overlay was partly visible from the game and I could easily click it if I needed to see it fully.

The current behavior is that either I check the lock option and the overlay obviously comes ontop of the game and is locked over it as it used to be, either I uncheck the option the same it was before and now the overlay isn't bring to the screen and seems rather hidden in the taskbar or wherever other place and user needs to pick it up manually, which is quite annoying to do every single game or draft.

Could we get the former behavior back, either by default or under an option/setting?

**Comment by Manuel-777** [comment] 2019-08-09 12:32
Hello!,
Can't you use `Alt + 1` to toggle the overlay visibility? With always on top enabled it should work, I don't think we changed how it works in the past weeks.

**Comment by Porkepix** [comment] 2019-08-09 12:43
I didn't knew about this shortcut, but even though I'm pretty much sure it used to be put on foreground just the layer behind mtga, at the very least for drafts and I believe also for games. Can't say for sure when did it change though.

**Comment by Manuel-777** [comment] 2019-09-03 03:42
Closing as wont-fix, since this is the current expected behavior of the overlays. (the overlays now behave as true overlays and not as another window in the desktop, so always on top is recomended and the toggles / shortcuts should provide more than enough flexibility)

**Closed by Manuel-777** 2019-09-03 03:42 UTC

**Comment by Porkepix** [comment] 2019-09-08 09:09
> Closing as wont-fix, since this is the current expected behavior of the overlays. (the overlays now behave as true overlays and not as another window in the desktop, so always on top is recomended and the toggles / shortcuts should provide more than enough flexibility)

Can we please reopen this @Manuel-777? The new 2.9.x overlays actually made the things even worse, and pretty much impossible to use with my current setup.
I'll explain the whole thing through:

First my setup, I'm mostly playing on an old screen with nowadays nonstandard definition (1280x1024).
Due to this mtga didn't allow for many window sizes, even though they now changed this. Still, this mostly isn't enough to have both the game window and overlays 100% visible all of the time due to not enough space.
For this reason, having game window and overlays just under it seems way better as you can still partially see the overlay and switch to see it completely whenever needed.

This used to be possible back to just before I opened this issue.

Now, the way it currently behaves:

- If user doesn't check "Always on top when shown", then overlays as a whole is a window buried under all the other ones. This is not a window you can switch over with alt-tab or the taskbar (new from 2.9.x), so that the only way to show it is to reduce all the other windows to finally get it, and don't interact  with those windows during games as it's gonna go over the overlay and you will run through the same issue again: no switch possible, need to reduce windows.
- Now if user checks "Always on top when shown", then overlays goes on-top of everything, sometimes even over the game itself and is pretty hard to get rid off so that it blocks interactions with everything else.

Either way, shortcuts only toggle overlay #n inside this new overlay thing with a black background itself (see joined screenshot)
![overlays](https://user-images.githubusercontent.com/709500/64486070-d07eb380-d228-11e9-8519-d813d03c0704.PNG)
It does not deal with foreground/background at all while I think it probably should (even behind a toggle/option).

I hope I was clear enough even though I'm not sure at all given how difficult it can be to reproduce the same result reliably every time, but I can answer any question or try to explain things another way.

**Comment by Porkepix** [comment] 2019-09-08 09:14
As an addition, but this might deserve a new issue: if overlay is set to be always on top and that you somehow ends up getting to the window in screenshot, including the black background, then it's pretty much locked on top of everything else, but clicks on the black zone are sent to the window under it.

**Comment by Manuel-777** [comment] 2019-09-08 16:23
The problem you have is with transparency actually, Do you have windows Aero enabled?

**Comment by Porkepix** [comment] 2019-09-08 17:17
Indeed I had it enabled. So after your comment I did some tries while disabling it. Unfortunately, I still encounter the same issues.
