### ISSUE TITLE
Overlay shows cards from previous game

### ISSUE THREAD

**Issue by omegaula** [Manuel-777/MTG-Arena-Tool#181] opened 2019-02-10 18:05 UTC
Version 2.2.17
Steps to repro:
- start a match (any kind)
- select "Cards played by opponent" tab in overlay
- play the game till done
- play another game
- overlay starts with cards from previous game and they don't disappear
- most of the time if at this point I switch to different tab (eg. showing my cards) and then play the next game, the opponent cards start empty

It seems that  "Cards played by opponent" tab needs to be active for this to happen.

**Comment by Manuel-777** [comment] 2019-02-10 23:25
Cant seem to reproduce, How do your overlay settings look like?

**Comment by omegaula** [comment] 2019-02-12 02:13
My settings:

![capture](https://user-images.githubusercontent.com/770780/52606805-e28aa600-2e41-11e9-9137-723450e1f39a.PNG)

**Comment by Manuel-777** [comment] 2019-03-09 19:25
I believe this was fixed in dev, since I pushed lots of data nad overlay improvements, please let me know if it is still happening after v2.2.21 release in the upcoming days

**Closed by Manuel-777** 2019-03-09 19:25 UTC
Labels: bug, needs more data, overlay
