### ISSUE TITLE
Completion in collection can show NaN percents

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1091] opened 2020-05-24 03:36 UTC
I opened quite a bunch of the Theror packs that I spared up to now. I could notice that in many places, it was showing NaN percent of the collection.

See screenshots below
![NaN_percent_Theros](https://user-images.githubusercontent.com/709500/82745062-43f92e80-9d80-11ea-86e5-55ccea2bc2e5.PNG)
![NaN_percent_Theros2](https://user-images.githubusercontent.com/709500/82745065-452a5b80-9d80-11ea-98d1-f5f5ee225cfc.PNG)

I am highly suspicious that it could come from the three squares that are invisible, where I own some copies of those cards, but Tool seems to have badly registered that.

**Comment by riQQ** [comment] 2020-05-24 09:13
Duplicate of #1082

**Comment by riQQ** [comment] 2020-05-24 09:13
Should be fixed with 4.2.9

**Closed by riQQ** 2020-05-24 09:13 UTC
