### ISSUE TITLE
App regularly asks for a password, despite "login automatically" is turned on

### ISSUE THREAD

**Issue by mitrrich** [Manuel-777/MTG-Arena-Tool#1141] opened 2020-07-08 19:20 UTC
Pretty much subject.
Logs will be sent via email.
Beta channel is used, however issue remains over several weeks(?) despite some app updates were done during that period

**Comment by Manuel-777** [comment] 2020-07-08 20:14
Inspecting the supplied logs it seems the cause is a token revoken on the server, I will continue to investigate revoked tokens see if there is something I missed there.

**Comment by Manuel-777** [comment] 2020-07-11 15:37
Tested the server implementations and it seems to be okay for the most part, only thing I noticed is the tokens will clear if you log in from a different machine, have you done that?

**Comment by riQQ** [comment] 2020-07-12 09:43
I'm having the same issue and I'm only using a single machine.

**Comment by mitrrich** [comment] 2020-07-14 18:57
No, I didnt login from anywhere else.
I sometimes login in browser using VPN (so it will look like different IP adress) but it's rarely the case and it wasnt like that when I sumbitted logs and opened an issue

**Comment by Magican28** [comment] 2020-07-15 06:14
I seem to have something related - after a Microsft Win 10 update Arena Tool came up with "remember me" tagged but wanting a password entered. But it wouldn't allow entry

Now I have lost my email address entry as well, and it won't let me enter that either

**Comment by riQQ** [comment] 2020-07-15 06:19
Sometimes my complete credentials are lost, i.e. Email + password.

**Comment by Magican28** [comment] 2020-07-15 11:41
Thanks riQQ - what do you do when your credentails are lost? Or does it just let you type them in again?

**Comment by riQQ** [comment] 2020-07-15 13:34
I type them in again. Sometimes the tool doesn't even react to me pressing the login button, then I have to restart to make it work again.

**Comment by Manuel-777** [comment] 2020-07-28 02:44
This is apparently fixed now, has anyone had any issues like this lately?

**Comment by riQQ** [comment] 2021-03-10 18:40
Haven't had this happen for a long time.

**Closed by riQQ** 2021-03-10 18:40 UTC
Labels: apparently fixed, bug
