### ISSUE TITLE
[linux] 4.2.10 not starting after install from source

### ISSUE THREAD

**Issue by bauris-prvt** [Manuel-777/MTG-Arena-Tool#1100] opened 2020-05-27 14:40 UTC
After installing 4.2.10 from source, `npm start` does not function properly and breaks with a `babel` issue. See pastebin for cli output, let me know, if the debug-log would be helpful.
[npm start cli output](https://pastebin.com/j5QnpMaR)

The 4.2.10 appimage does run without any issues whatsoever.

I will stop using the source releases going forward, since I do not really want to clog-up the tracker with these issues. I am not familiar with developing applications in this particular environment so all this stuff might as well be problems on my end. I will stick to running the appimage releases.

Cheers, very much appreciate the arena tool and all the effort from you guys.

**Comment by riQQ** [comment] 2020-06-04 11:35
Duplicate of #1077

**Closed by riQQ** 2020-06-04 11:35 UTC
