### ISSUE TITLE
Column headers in Economy tab can be misaligned on various resolutions

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1095] opened 2020-05-24 09:48 UTC
See examples on these screenshots:

Taken from a QHD (2560x1440) screen:
![Economy headers](https://user-images.githubusercontent.com/709500/82750953-3b225000-9db4-11ea-8b26-ab3ffbe0b877.PNG)

Taken from a 1280x1024 screen:
![economy_column_headers](https://user-images.githubusercontent.com/709500/82750960-44abb800-9db4-11ea-88ca-5e0b3927be06.PNG)

As I can manage to start Tool on my FHD Linux laptop, I can't test this resolution, but considering it has become the most common one, I'd guess that this one have no issue, but that it doesn't adapt very well to other resolutions.

**Comment by Thaoden** [comment] 2020-05-24 10:08
The headers are mainly for the table view, IIRC.

**Comment by Manuel-777** [comment] 2020-05-24 12:42
Yup, list view is not a table. closing as its not a bug.

**Closed by Manuel-777** 2020-05-24 12:42 UTC
