### ISSUE TITLE
Time error

### ISSUE THREAD

**Issue by aroundightii** [Manuel-777/MTG-Arena-Tool#400] opened 2019-05-28 03:44 UTC
When I finish my first daily quest, I get 500$. But in the economy part, it shows that I get 500$ in 1 Jan 1970. I have no idea why this would happen. Anyone can help me fix this problem?

**Comment by Manuel-777** [comment] 2019-05-28 03:49
Duplicate of #399

**Closed by Manuel-777** 2019-05-28 03:49 UTC
