### ISSUE TITLE
Dates in the economy view are in the future

### ISSUE THREAD

**Issue by liberforce** [Manuel-777/MTG-Arena-Tool#239] opened 2019-03-29 00:13 UTC
In the economy view, the dates shown are already in 2020, but with a mention in the past (like "471 days ago"). Both are incorrect. I started playing circa november 2018, so around 130 days ago.

Here's a screenshot:
![mtgatool-future](https://user-images.githubusercontent.com/252242/55200508-b98a5e80-51be-11e9-9b0a-7400674d4800.png)

This problem is not recent, I first saw this 2 or 3 months ago.
I'm running the latest version, 2.2.21.
I did some errors in the developer console, but I'm not sure they are relevant. Sorry, I couldn't find how to export them, in text format, so here's a screenshot:

![mtgatool-future-with-logs](https://user-images.githubusercontent.com/252242/55200703-a88e1d00-51bf-11e9-98d3-29bda71e0cd0.png)

Could you please point to instruction on which log files to send for further investigation?
Thanks

**Comment by Manuel-777** [comment] 2019-03-29 01:31
Hello @liberforce !
This issue is one I tried to find a long time ago but never got around the cause. My main suspicion is MTGA Language, what language is yours?

The log files we use to debug are found at `%APPDATA%\..\LocalLow\Wizards Of The Coast\MTGA\output_log.txt`, If you can please share that file at `mtgatool@gmail.com` for us to analyze, if you have a new reward in the logs that would be ideal (to compare the dates tool is reading)

**Comment by liberforce** [comment] 2019-03-29 11:19
Hi, thanks for your quick reply.
My MTGA client was configured in french at first, but I switched to english a couple of months ago.

As for the rewards, there should be plenty of them, I didn't clear the logs and since the MTGA client update released 2 days ago, there are the Mastery Tree rewards that start showing up. I had all the preconstructed decks so I now receive the rewards automatically, in an "hidden" way. They show up under the "PlayerProgression.OrbSpend" category in the economy view. I just checked, the dates associated to this event are correct.

Today I played a Ravnica Allegiance draft in BO1 format, was rewarded 2 booster packs, and opened my first "Absorb" if you need a comparison point.

The inconsistencies I saw:
- there are games in the future, as you can see in the screenshots
- most dates in 2018 are wrong, I started playing around november 2018, but I see games being reported _months_ earlier that year

**Comment by liberforce** [comment] 2019-03-29 11:20
Here are the logs, it's probably easier to keep them inside the bug report.
[output_log.zip](https://github.com/Manuel-777/MTG-Arena-Tool/files/3022394/output_log.zip)

**Comment by AnnanFay** [comment] 2019-03-30 22:03
@liberforce 
I've had a look at the logs and all the dates are correct. However, Arena Tool wasn't using the log file dates for economy transactions anyway but local system time. The only 2020 dates in the log file are for event ending dates - Constructed Event is set to end at `2020-04-01T16:00:22Z` for example, but that's in everyone's log file.

So - I have no idea what is causing this, but it's not caused by weird dates in the log file.

If you have your local settings file handy it might show more insight - `W5FQ26WGI5FJHN5LM4TFDLT3OQ.json` file in `%APPDATA%\MTG-Arena-Tool\`.

What version of windows are you running on?

One thing which could have happened is a bug with date parsing a few months ago could have parsed events as happening in 2020 so they remain at the top of the screen - since it sorts by date. You say new events are working correctly?

If the bug was fixed you would still see the 2020 transactions because they are the 'most recent' and new events would be added below the bugged events.

**Comment by liberforce** [comment] 2019-03-31 22:55
@AnnanFay 
I'm running Windows 7. The json file indeed has lots of 2020 dates in it. Here it is. Thanks for giving a look at this.
[W5FQ26WGI5FJHN5LM4TFDLT3OQ.zip](https://github.com/Manuel-777/MTG-Arena-Tool/files/3027245/W5FQ26WGI5FJHN5LM4TFDLT3OQ.zip)

**Comment by liberforce** [comment] 2019-04-03 09:46
@Manuel-777 Any news on this? Just pinging in case I should have mentionned you in my previous comments.

**Comment by Manuel-777** [comment] 2019-04-03 10:29
#241 Did some progress on this but still needs to be tested, next update will have it!

**Comment by liberforce** [comment] 2019-04-04 07:11
Nice! I'll test it as soon as it's released. Is it supposed to automatically fix past events, or will I need to delete some cache files to have those events parsed again?

**Comment by AnnanFay** [comment] 2019-04-07 11:45
Okay, so I [extracted the dates](https://gist.githubusercontent.com/AnnanFay/545ef0d83d0d18c8da4742ebc66022d1/raw/bb591f25537bb7920fdea2bb4630e78b44006a66/Economy%2520Dates:%2520W5FQ26WGI5FJHN5LM4TFDLT3OQ) from the data.

All dates ending in `000Z` are created by parsing the output log. Other dates are created using `new Date()` and reflect when the log was *parsed*, not when the event happened.

All dates in the future (bad-dates) are 000Z created by parsing the output log data. These are probably from a while ago. Right now there are 249 events in the future which will always be at the top of the economy screen.

#241 won't fix any existing bad data. Unless you have previous log files then the data is gone forever. The best fix is to detect bad dates and flag the events as `corrupt` so they don't appear in the economy screen.

The *safest* method to do this is when loading the economy data, something like: ```javascript
if (new Date(transaction.date) > now && transaction.date.endsWith('000Z')) {
    transaction.bad = true;
    save(transaction);
}```

This won't fix any of the data but will hide it. If someone does have old log files backed up and reparses the economy events then it will override the objects with new dates.

**Comment by liberforce** [comment] 2019-04-17 08:45
This is not fixed. I tried the latest version yesterday.
What happens is that the dates don't show the year anymore, and the "X days ago" text is gone, but I can still see those events as the first entry that is shown is in july, and last july I hadn't started playing.

So I think that:
- the year should be displayed, as it's a valuable information (had I started to play in july I could probably not have noticed the problem)
- the events that have a date in the future should be at the very bottom of the list, to avoid masking recent events

Maybe just grouping the events with dates in the future in an "unknown date" category for the event marked in the future would be enough. With this section at the end of the list, the data would still visible, but wouldn't mask recent history, which is my main concern here.

**Comment by liberforce** [comment] 2019-04-23 09:54
Any news on this?

**Comment by Manuel-777** [comment] 2019-04-27 17:13
The patch is already in release! so new events should be okay, but old ones will still be visible in the wrong date/order

**Comment by liberforce** [comment] 2019-04-29 16:38
Your patch only fixes a part of the problem then. It's nice and will avoid to make things worse with new event, but as I already said, having events in the future visible makes the complete view useless, as I can't see what I won today or yesterday easily, as the first events that are shown to me are events I don't care about.
Can something be done about that, or do I need to edit the json by hand to remove them?

**Comment by Manuel-777** [comment] 2019-04-29 16:41
Sorry for the delay on this! I plan to add the ability to either delete entries individually or by bulk to economy, ill hopefully push an update as soon as it's ready.

**Comment by liberforce** [comment] 2019-04-29 16:50
Thanks, that would be great :+1:

**Comment by Manuel-777** [comment] 2019-05-13 10:58
Added in latest release, closing :)

**Closed by Manuel-777** 2019-05-13 10:58 UTC
Labels: bug, economy
