### ISSUE TITLE
Password reset fails with "something went wrong." when email address contains "+"

### ISSUE THREAD

**Issue by david-in-perth** [Manuel-777/MTG-Arena-Tool#263] opened 2019-04-16 16:14 UTC
I tried to use the [password reset page][] to reset the password of my account (which I had just created). The page responded with "something went wrong.".

I suspect it might have been caused by a failure to handle the "+" in the email address that I used. See [this discussion of the validity of + in email addresses][plus-is-valid].

[password reset page]: https://mtgatool.com/resetpassword/
[plus-is-valid]: http://www.jacobsen.no/anders/blog/archives/2002/08/24/email_addresses_with_a_are_valid.html

**Comment by Manuel-777** [comment] 2019-04-16 21:58
It was not a restriction on my side, but rather an encoding problem, email was not being properly encoded/decoded thus the special characters were lost in the transaction.
Next update will fix it! Thanks ! :D

**Comment by david-in-perth** [comment] 2019-04-29 16:26
@Manuel-777: I'm still getting the same error on the password reset page. Is the fix in e2a6c8b just for the login screen on the app?

![image](https://user-images.githubusercontent.com/558809/56910773-eee7dc00-6add-11e9-977e-61454ff25481.png)

**Comment by Manuel-777** [comment] 2019-04-29 16:28
That seems like a server sided issue!

**Comment by david-in-perth** [comment] 2019-05-09 13:44
@Manuel-777: I'm still getting the "something went wrong." message on the password reset page. Do I need to wait for an update to be deployed to the server?

**Comment by Manuel-777** [comment] 2019-05-09 13:45
No, it should be fixed now, send me your login email at mtgatool@gmail.com

**Comment by QuinRiva** [comment] 2019-06-15 03:28
I'm also getting the issues, notably I also have a **+** character in my email address.  Potentially this might be the cause?

**Comment by Manuel-777** [comment] 2019-06-15 03:58
It probably is! Ill try make an exception for it since it seems to be escaped by the system

**Comment by david-in-perth** [comment] 2019-12-22 08:45
@Manuel-777: Any news on this? Is there a repo for the server source code?

**Comment by riQQ** [comment] 2019-12-22 10:06
> @Manuel-777: Any news on this? Is there a repo for the server source code?

https://github.com/mtgatool/mtgatool-web

**Closed** 2020-04-24 18:23 UTC

**Comment by david-in-perth** [comment] 2020-04-25 00:33
This is still a problem for me. I'll log a new ticket under https://github.com/mtgatool/mtgatool-web
