### ISSUE TITLE
Match where opponent conceded during sideboard is not counted as a win

### ISSUE THREAD

**Issue by SabreCat** [Manuel-777/MTG-Arena-Tool#610] opened 2019-10-04 12:51 UTC
Had a Bo3 game this morning where I lost game 1, then won game 2 and the opponent conceded out during sideboarding, awarding me the match. However, in the History view the match win:loss readout shows in red as if I'd lost:

![image](https://user-images.githubusercontent.com/4501321/66208600-10478800-e67b-11e9-9b15-cacbe2ee25d3.png)

In deck stats, it appears that this outcome isn't tallied at all. I currently have 6 Bo3 matches in current season with this deck, 5 wins (counting the above) and 1 loss, but on the My Decks screen my record shows as 4:1.

I'd expect a green readout on History and a win counted in Decks.

**Comment by AnnanFay** [comment] 2019-10-04 18:44
Duplicate of #571

**Closed by AnnanFay** 2019-10-04 18:44 UTC
Labels: bug, duplicate
