### ISSUE TITLE
Server unreachable, try offline mode

### ISSUE THREAD

**Issue by gormleymark** [Manuel-777/MTG-Arena-Tool#247] opened 2019-04-06 17:28 UTC
I frequently get this when trying to open arena tool. Not firewall related as it happens when I disable it.

**Comment by phattrent** [comment] 2019-04-06 20:32
Same, I get offline mode all the time, rarely able to login these days.

**Comment by Manuel-777** [comment] 2019-04-06 23:26
I need some more data to know what is going on, try this;
- Press `Alt` + `Shift` + `D`
- Find the Developer Tool's window named `/window_background/index.html`
- Find the `Console` tab
Paste a screenshot of that log, all of it if possible. There should probably be a server response that was not expected by the client.

**Comment by gormleymark** [comment] 2019-04-07 00:07
![image](https://user-images.githubusercontent.com/6172162/55676712-796b6000-58d1-11e9-92ea-2355a3d09445.png)

**Comment by Manuel-777** [comment] 2019-04-07 00:17
Are you running from source? All I could find related to that issue was a DNS problem, but no single solution. If you are running from source I would try updating npm, if not, either try a different network or use a different DNS address to (like google's `8.8.8.8`)

**Comment by phattrent** [comment] 2019-04-07 01:55
In fact, when I pressed alt shift D, the login button was enabled for me again (otherwise always greyed out) and I was able to login.

**Comment by Manuel-777** [comment] 2019-04-07 03:00
Most probably not related to the key pressing as that only brings the dev tools, could you send an image of the `Console` tab like gormleymark's when the error occurs again?
Thanks!

**Comment by ironocy** [comment] 2019-04-08 00:28
I just installed and can't sign in. Unclear why. I enter my credentials and click Login but nothing happens. I tried clicking Alt + Shift + D but can't find the developer tools you reference, honestly, I'm not even sure what that means. I can find the console tab but that's about it. I disabled firewall, not running AV, not sure what's going on. How do I login?
![MTG Tools](https://user-images.githubusercontent.com/49377788/55692193-365dcb00-596b-11e9-9b2e-ec43fd7aa381.png)

**Comment by gormleymark** [comment] 2019-04-08 22:55
I tried Googles DNS and it worked initially but now it's back to server unreachable. Tried Open DNS also.

**Comment by liberforce** [comment] 2019-04-10 14:36
Maybe that's unrelated, but as I'm connecting to the internet from my laptop through my cell phone, if Arena Tool is trying to connect and the internet connection hasn't been fully set up yet, Arena Tool fails to connect. The problem is that it won't retry later, and that default comportment when closing it is to go to the tray. So one have to explicitly stop the application and re-run it after the internet is connected.

This means that if Arena Tool is setup to be launched at startup (which is the default setting, if I remember well), then it might run before before the internet connection is ready. If you're connected through a wireless connection, then I recommend either:
- testing with a wired connection
- disabling the "run at startup" option, disable the "close to tray" option, and make sure you run Arena Tool only after the internet is available

Tehn open Arena Tool and see if it connects. If it doesn't, try to close it and re-open.

**Comment by gormleymark** [comment] 2019-04-13 13:01
I've tried all that and nothing helped.

**Comment by gormleymark** [comment] 2019-04-16 15:19
Running from source seems to be the fix here - 3 days with no issue but it's a pain to have to run it from the command line.

**Comment by Nelthorim** [comment] 2019-04-21 07:37
Even running from source, I get the same error after updating to the newer version. This is the output in the command line:

```e": {
    "id": "hw05s0gzqdcs",
    "name": "MTG Arena",
    "url": "https://magicthegatheri
IPC LOG:  httpAsync:
IPC LOG:  SEND >> 0, auth, NecuLB, 6336931e6c43c019ce48d209d774065f26589b8a
IPC LOG:  RECV << 0, auth, NecuLB, 6336931e6c43c019ce48d209d774065f26589b8a
IPC LOG:  RECV << 0, auth, <br />
<b>Fatal error</b>:  Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitabl
IPC LOG:  httpAsync:

**Closed** 2019-08-21 16:44 UTC
Labels: bug, needs more data
