### ISSUE TITLE
Database Read Error

### ISSUE THREAD

**Issue by Spencer-Thalia** [Manuel-777/MTG-Arena-Tool#1061] opened 2020-05-07 08:46 UTC
Hi all,

Approximately 4 days ago my MTG-Arena Tool started showing this error: ![MTGA Tool Bug](https://user-images.githubusercontent.com/64954824/81273550-ef974480-9046-11ea-9861-484c4005c088.jpg)

Possible culprit to cause the bug was a win by time-out against a bant deck. That game shows up in my games played, but it does not register any result for that game. The image above displays whenever I click to see my constructed rank tab and it will then redirect me to the My Decks tab instead.

What's the easiest way to go in and sanitise the data? Should I wipe all of the data and start again?

**Comment by Manuel-777** [comment] 2020-05-10 18:00
Duplicate of #1065 

If you know for certain that match is the faulty one, you can try the following;
- Go to Decks tab and set the Time filter to "24 hours"
- Go to history tab, see if it works
- (in history) Set the View to "Table View"
- Set the time filter to "All Time"
- In "Show Column Toggles" make sure the archive (eye) icon is enabled.
- Find the match you think is faulty and archive it.
- Try using the "List View" now, if the error persists, then the faulty match is a different one.

**Comment by Spencer-Thalia** [comment] 2020-05-10 20:39
This solution worked. Thank you very much Manuel-777.

**Comment by Manuel-777** [comment] 2020-05-12 15:26
Alritght, closing this one! Glad it worked :)

**Closed by Manuel-777** 2020-05-12 15:26 UTC
Labels: bug, history
